version: '3.1'
services:
  app:
    build:
      context: .
    environment:
      - DB_HOST=postgres
      - DB_USER=dev
      - DB_PASSWORD=P4ssw0rd
      - DB_NAME=bringel
      - ALLOWED_HOSTS=*
      - SECRET_KEY=qi2r^v#s8ptux7%@_*hib*yyz+jn0s=@k4ny6)8@k!7fq8d!*x
    depends_on:
      - postgres
  postgres:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=P4ssw0rd
      - POSTGRES_USER=dev
      - POSTGRES_DB=bringel
