# Generated by Django 4.2.4 on 2023-09-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=8, unique=True, verbose_name='SKU'),
        ),
    ]
