name: Run tests
on: [push]
env:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  SECRET_KEY: "TEST_SECRET_KEY"
  DB_HOST: "NOT_USED_FOR_TESTING"
  DB_USER: "NOT_USED_FOR_TESTING"
  DB_PASSWORD: "NOT_USED_FOR_TESTING"
  DB_NAME: "NOT_USED_FOR_TESTING"
  CELERY_BROKER_URL: "NOT_USED_FOR_TESTING"
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint
      run: |
        make lint
    - name: Unittests
      run: |
        make test
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: htmlcov
        retention-days: 3
